#! python3

"""
Create a data structure for all type of fittings.

"""

import Units from uc
import Line from lines

class Fittings:
    def __init__(self, class, size):
        self.class = class
        self.size = size

class Pipe(Fittings):
    
    def __init__ (self, line, size = Units('L',2), schedule = 'std', length = Units('L', 10)): #TODO create a class or dictionary for piping class.
        self.line = line
        self.size = size
        self.schedule = schedule
        self.length = length
        
    @property
    def ID(self):
        pass
    
    def OD(self):
        pass
    
    def thinkness(self):
        pass
    
    def volume(self):
        pass
    
    def weight(self):
        pass
    
    def fractionloss(self):
        
        
    
    
class Elbow(Fittings):
  

class Tee(Fittings):
    

class Valve(Fittings):
    


    

class Reducer(Fittings):
    
    
class Entrance(Fittings):
    
    
class Exit(Fittings):
    
   
class SpecialItem(Fittings):
    

class Other(Fittings):
    
    
    
    
    
    
    
    
    
