#! python3

"""
Create a data structure for all type of fittings.

"""

import Units from uc

class Fittings:
    def __init__(self, class, size):
        self.class = class
        self.size = size

        
class Elbow(Fittings):
  

class Tee(Fittings):
    

class Valve(Fittings):
    

class Pipe(Fittings):
    

class Reducer(Fittings):
    
    
class Entrance(Fittings):
    
    
class Exit(Fittings):
    
   
class SpecialItem(Fittings):
    

class Other(Fittings):
    
    
    
    
    
    
    
    
    
